apiVersion: "prometheus.coreos.com/v1"
kind: "ServiceMonitor"
metadata:
  name: "node-exporter"
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  endpoints:
  - port: "scrape"

