apiVersion: "prometheus.coreos.com/v1"
kind: "Prometheus"
metadata:
  name: "prometheus-main"
  labels:
    prometheus: "main"
spec:
  serviceMonitors:
  - name: example-app
    endpoints:
    - name: web
      scrapeInterval: 10s
