apiVersion: "monitoring.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: "prometheus-main"
  labels:
    prometheus: "main"
spec:
  replicas: 2
  version: v1.4.0
  serviceMonitorSelector:
    matchExpressions:
    - {key: app, operator: In, values: [node-exporter, example-app]}
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager-main
  resources:
    requests:
      memory: 400Mi
