apiVersion: "prometheus.coreos.com/v1alpha1"
kind: "Prometheus"
metadata:
  name: "prometheus-main"
  labels:
    prometheus: "main"
spec:
  serviceMonitors:
  - selector:
      matchLabels:
        app: example-app
  - selector:
      matchLabels:
        app: node-exporter
