apiVersion: "prometheus.coreos.com/v1"
kind: "Prometheus"
metadata:
  name: "prometheus-main"
  labels:
    prometheus: "main"
spec:
  monitors:
  - selector:
      matchLabels:
        app: example-app
  rules:
  - name: "example-app-alerts"

