sudo: required
language: go
go:
- 1.9
services:
- docker
jobs:
  include:
  - stage: Check generated contents are up to date and code is formatted.
    script: ./scripts/check-make-generate.sh
  - stage: Ensure vendor folder matches vendor.json
    script: ./scripts/govendor-ensure.sh
  - stage: Unit tests
    script: make test
  - stage: E2e tests
    script: travis_wait 30 ./scripts/travis-e2e.sh
