sudo: required
language: go
go:
- 1.9
services:
- docker
before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
jobs:
  include:
  - stage: Check generated contents are up to date and code is formatted.
    script: ./scripts/check-make-generate.sh
  - stage: Build Prometheus config reloader
    script: cd contrib/prometheus-config-reloader && make build
  - stage: Ensure vendor folder matches vendor.json
    script: ./scripts/govendor-ensure.sh
  - stage: Unit tests
    script: make test
  - stage: E2e tests
    script: ./scripts/travis-e2e.sh
  - stage: E2e helm
    script: ./scripts/travis-e2e-helm.sh

deploy:
  provider: script
  script: helm/hack/helm-package.sh "alertmanager grafana prometheus prometheus-operator exporter-kube-api \
                exporter-kube-dns exporter-kube-scheduler exporter-kubelets exporter-node \
                exporter-kube-controller-manager exporter-kube-etcd exporter-kube-state exporter-kubernetes" && \
        helm/hack/sync-repo.sh && \
        helm/hack/helm-package.sh kube-prometheus && \
        helm/hack/sync-repo.sh
  on:
    branch: master
