apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: prometheus-frontend
  namespace: default
  labels:
    prometheus: frontend
spec:
  version: v1.3.0
  serviceMonitors:
  - selector:
      matchLabels:
        tier: frontend
