apiVersion: prometheus.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: default
  labels:
    team: frontend
spec:
  selector:
    matchLabels:
      team: frontend
  scrapeInterval: 10s
  endpoints:
  - port: web