apiVersion: v1
kind: Service
metadata:
  name: kube-dns-prometheus-discovery
  labels:
    k8s-app: kube-dns
  annotations:
    prometheus.io/scrape: 'true'
spec:
  selector:
    k8s-app: kube-dns
  type: ClusterIP
  clusterIP: None
  ports:
  - name: prometheus
    port: 8082
    targetPort: 8082
    protocol: TCP
