apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: persisted
spec:
  storage:
    volumeClaimTemplate:
      metadata:
        volume.beta.kubernetes.io/storage-class: ssd
      spec:
        resources:
          requests:
            storage: 40Gi
