apiVersion: monitoring.coreos.com/v1alpha1
kind: Prometheus
metadata:
  name: example
spec:
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  version: v1.5.2
  resources:
    requests:
      memory: 400Mi
